### ISSUE TITLE
Revert back to centre coordinate and write out dimensions of ROI

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/immucan-roi#11]
Hey @jwindhager 
could you please revert back the selection to the centre coordinate? For us to post-process the ROIs, we would also need information regarding the x/y dimensions of the selected ROIs.
Does that sound alright?
Cheers,
Nils

**Comment by jwindhager** [comment]
Happy to change it back. Also, would you like me to include the post-processing in `immucan-roi`? It's a project-specific software anyway, happy to customize it

**Comment by nilseling** [comment]
Thanks a lot! For now I think the centre coordinate and width/height is enough. We have an issue that we need to specify the position name of the sample based on its coordinates on the slide. So far this is something that we can only do post-hoc.

**Comment by jwindhager** [comment]
Let's discuss offline

**Comment by jwindhager** [comment]
Dimensions should already be written out in micrometers (as both napari-czifile2 and napari-imc load the images in machine coordinates in micrometer). Please let me know if this is not the case.

**Comment by nilseling** [comment]
It seems that the centre setting does not produce correct results after transformation. Reopening just to keep this in mind.

**Comment by jwindhager** [comment]
Fixed with v0.2.5
