### ISSUE TITLE
scrolling through a set of image pairs more than once alters the mcd coordinates (v0.2.3)

### ISSUE THREAD

**Issue by michdaniel** [BodenmillerGroup/immucan-roi#14]
If you go through all the image sets once, the ROI coordinates are correct when imported into the mcd file. If you then scroll back around to the first image set without closing the tool the mcd coordinate csv file is resaved even without moving the ROIs. The issue is that this gives rise to new coordinates which are very off. I did a test with 3 images where in the first round I set alignment points and ROIs and saved the transformed mcd coordinates. I then scrolled through the images twice more copying the coordinates elsewhere each time, then closed the tool and scrolled again 3 times for a total of 6 times, each time saving the coordinates. Attached are the coordinates for the first image. top row is original values, second and third rounds. Bottom row is fourth to sixth.  

[composite_10038218.csv](https://github.com/BodenmillerGroup/immucan-roi/files/8740012/composite_10038218.csv)

It's clear the coordinates change after the first round then not again, even after restarting the tool. The other two images show the same result. 

I don't know if this happens in other versions of the tool.

**Comment by jwindhager** [comment]
Fixed with v0.2.5
