### ISSUE TITLE
Creates .DS_Store.csv

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/immucan-roi#9]
Hey @jwindhager,
this is a mac issue due to the presence of `.DS_Store` files. Would it be possible to avoid reading in hidden files?

**Comment by jwindhager** [comment]
Please let me know if v0.2.1 fixes this, thanks

**Comment by jwindhager** [comment]
Potentially in napping

**Comment by jwindhager** [comment]
Could you tell me, in which subdirectory this file is created?

**Comment by nilseling** [comment]
The issue comes from `czi/.DS_Store`. From there the `czi_roirs/.DS_Store.csv` file is created.
But I'm not sure if `immucan-roi` creates it or the OS when fiddling around with the folders.

**Comment by jwindhager** [comment]
This really should've been fixed with https://github.com/BodenmillerGroup/immucan-roi/commit/a35fec787bb9cac9bd48ea2bd4b7df5b0a1618ad - are you sure this issue still persists?

**Comment by nilseling** [comment]
I can confirm that with v0.2.2 it's still an issue. The error is "Number of source files does not match the number of target files"

**Comment by jwindhager** [comment]
Closing for now. Let me know if it reappears and show me on site, please!
